name: Build Module

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with: { java-version: '17' }
    - uses: gradle/actions/setup-gradle@v3
      with: { gradle-version: '8.9' }
    - run: ./gradlew :app:assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
